# SPDX-FileCopyrightText: Copyright 2020-2026, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
changelog:
  exclude:
    authors:
      - "github-actions[bot]"
    labels:
      - "changelog: exclude"
  categories:
    - title: 💥 Breaking changes
      labels:
        - breaking
    - title: ❌ Removals
      labels:
        - "type: drop"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: 🗑️ Deprecations
      labels:
        - "type: deprecation"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: 🔒️ Security
      labels:
        - "type: security"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: ✨ Features
      labels:
        - "type: feature"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: 🐛 Fixes
      labels:
        - "type: fix"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: ⚡️ Performance
      labels:
        - "type: performance"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: 📝 Documentation
      labels:
        - "type: docs"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: "🔧 Build"
      labels:
        - "type: build"
      exclude:
        - "scope: dev-infra"
        - "scope: docs-infra"
    - title: "🛠️ Miscellaneous"
      labels:
        - "changelog: include" # E.g. style and chore
        - "type: refactor"
        - "type: test"
        - "type: ci"
        - "scope: dev-infra"
        - "scope: docs-infra"
