# Documentation config.
# https://zensical.org/docs/setup/basics/

[project]

# ::tyranno:: site_name = "$<<project>>"
site_name = "tyranno-sandbox"
# ::tyranno:: LABEL site_url = "$<<project.urls.Documentation>>"
site_url = "https://dmyersturnbull.github.com/tyranno-sandbox"
# ::tyranno:: repo_url = "$<<project.urls.Homepage>>"
repo_url = "https://github.com/dmyersturnbull/tyranno-sandbox"
# ::tyranno:: copyright = "$<<.copyright>>"
copyright = "Copyright 2020–2026, Contributors to Tyrannosaurus"
# ::tyranno:: site_description = "$<<project.description>>"
site_description = "Sandbox for Tyrannosaurus"
# ::tyranno:: site_author = "The $<<project.name>> team"
site_author = "The Tyrannosaurus team"
language = "en"

extra_css = [
  "css/extra.css"
]
extra_javascript = [
  "js/mathjax.js",
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js",
  "js/tablesort.js",
  "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js",
]

# **Most** of these built-in extensions are enabled by default:
# https://zensical.org/docs/setup/extensions/
# **Some** PyMdownX extensions are enabled by default:
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/

# [project.markdown_extensions.abbr]

# https://zensical.org/docs/setup/extensions/python-markdown/#abbreviations
[project.markdown_extensions.admonition]

# https://zensical.org/docs/setup/extensions/python-markdown/#attribute-lists
# [project.markdown_extensions.attr_list]

# https://zensical.org/docs/setup/extensions/python-markdown/#definition-lists
# [project.markdown_extensions.def_list]

# https://zensical.org/docs/setup/extensions/python-markdown/#footnotes
[project.markdown_extensions.footnotes]

# https://zensical.org/docs/setup/extensions/python-markdown/#markdown-in-html
[project.markdown_extensions.md_in_html]

# https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
[project.markdown_extensions.pymdownx.arithmatex]
inline_syntax = ["dollar"]
block_syntax = ["dollar", "begin"]

# https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/
[project.markdown_extensions.pymdownx.blocks.caption]

# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#details
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"

# https://facelessuser.github.io/pymdown-extensions/extensions/fancylists/
[project.markdown_extensions.pymdownx.fancylists]

# https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums_style = "pymdownx-inline"
pygments_lang_class = true
line_spans = "line"

# https://facelessuser.github.io/pymdown-extensions/extensions/keys/
[project.markdown_extensions.pymdownx.keys]

# https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
[project.markdown_extensions.pymdownx.magiclink]
repo_url_shortener = true
repo_url_shorthand = true

# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#superfences
[project.markdown_extensions.pymdownx.superfences]

# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#tabbed
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

# https://zensical.org/docs/setup/extensions/python-markdown/#tables
[project.markdown_extensions.tables]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = true

[project.theme]
features = [
  "navigation.expand",            # https://zensical.org/docs/setup/navigation/#navigation-expansion
  "navigation.footer",            # https://zensical.org/docs/setup/footer/#navigation
  "navigation.indexes",           # https://zensical.org/docs/setup/navigation/#section-index-pages
  "navigation.instant",           # https://zensical.org/docs/setup/navigation/#instant-navigation
  "navigation.instant.progress",  # https://zensical.org/docs/setup/navigation/#progress-indicator
  "content.footnote.tooltips",     # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
  "navigation.path",              # https://zensical.org/docs/setup/navigation/#navigation-path
  "navigation.sections",          # https://zensical.org/docs/setup/navigation/#navigation-sections_1
  "navigation.tracking",          # https://zensical.org/docs/setup/navigation/#anchor-tracking
  "search.highlight",             # https://zensical.org/docs/setup/search/#search-highlighting
  "toc.follow",                   # https://zensical.org/docs/setup/navigation/#anchor-following
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
