# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: check-hooks
description: Runs basic pre-commit hooks.
inputs:
  ref:
    default: ""
    description: A branch or tag ref; defaults to github.head_ref then to github.ref.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref || github.head_ref || github.ref }}
    - uses: astral-sh/setup-uv@v7
    - name: Sync and confirm lock file is up-to-date
      shell: bash
      run: |
        uv sync --frozen --only-group precommit
    - uses: extractions/setup-just@v3
    - name: Run pre-commit hooks
      shell: bash
      run: |
        just check-simple
