# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: check-mkdocs
description: Checks that 'mkdocs build' works.

inputs:
  ref:
    default: ""
    description: A branch or tag ref; defaults to github.head_ref then to github.ref.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref || github.head_ref || github.ref }}
    - uses: astral-sh/setup-uv@v6
    - shell: bash
      run: |
        uv sync --locked --only-group docs
        uv run --no-sync mkdocs build --strict
