# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: lint-helm-charts
description: Lints Helm charts.

inputs:
  ref:
    default: ""
    description: A branch or tag ref; defaults to github.head_ref then to github.ref.
  compare-to-ref:
    description: >-
      Only check Helm charts that differ from this ref.
      If '*', runs on all charts.
      Defaults to github.base_ref then to '*'.
  chart-dirs:
    default: charts/,helm/,helm/charts/
    description: Comma-separated list of directories containing charts.

runs:
  using: composite
  steps:
    - id: define
      shell: bash
      run: |
        ref='${{ inputs.ref || github.head_ref || github.ref }}'
        base='${{ inputs.compare-to-ref || github.base_ref || '' }}'
        echo "ref=$ref" >> "$GITHUB_OUTPUT"
        echo "base=$base" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v6
      with:
        ref: ${{ steps.define.outputs.ref }}
    - uses: astral-sh/setup-uv@v7 # Some subsequent tools expect Python.
      with:
        activate-environment: true
    - uses: azure/setup-helm@v4.3.0
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.7.0
    - if: ${{ steps.define.outputs.base }}
      name: Run chart-testing (ct lint) on changed charts
      shell: bash
      run: |
        ct lint \
          --since '${{ steps.define.outputs.base }}' \
          --chart-dirs '${{ inputs.chart-dirs }}' \
          --use-helmignore \
          --github-groups
    - if: ${{ ! steps.define.outputs.base }}
      name: Run chart-testing (ct lint) on all charts
      shell: bash
      run: |
        ct lint \
          --all \
          --chart-dirs '${{ inputs.chart-dirs }}' \
          --github-groups
