# SPDX-FileCopyrightText: Copyright 2020-2026, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: get-paths
description: Summarize paths that changed with respect to a base

inputs:
  ref:
    default: ""
    description: A branch or tag ref; defaults to github.head_ref then to github.ref.
  base:
    default: ""
    description: The ref to compare against; defaults to github.base_ref

outputs:
  compose:
    description: >-
      'true' if 'compose.yaml' was modified; otherwise ''
    value: ${{ steps.paths.outputs.compose == 'true' || '' }}
  docs:
    description: >-
      'true' if 'docs/', 'zensical.toml', etc. was modified; otherwise ''
    value: ${{ steps.paths.outputs.docs == 'true' || '' }}
  docker:
    description: >-
      'true' if 'Dockerfile' or '.dockerignore' was modified; otherwise ''
    value: ${{ steps.paths.outputs.docker == 'true' || '' }}
  git:
    description: >-
      'true' if '.gitignore' or '.gitattributes' was modified; otherwise ''
    value: ${{ steps.paths.outputs.git == 'true' || '' }}
  readme:
    description: >-
      'true' if '/*.md' or 'LICENSE.txt' was modified; otherwise ''
    value: ${{ steps.paths.outputs.readme == 'true' || '' }}
  setup:
    description: >-
      'true' if 'pyproject.toml' was modified; otherwise ''
    value: ${{ steps.paths.outputs.setup == 'true' || '' }}
  src:
    description: >-
      'true' if 'src/' was modified; otherwise ''
    value: ${{ steps.paths.outputs.src == 'true' || '' }}
  tests:
    description: >-
      'true' if 'tests/' was modified; otherwise ''
    value: ${{ steps.paths.outputs.tests == 'true' || '' }}
  tools:
    description: >-
      'true' if 'justfile', 'biome.jsonc', etc. was modified; otherwise ''
    value: ${{ steps.paths.outputs.tools == 'true' || '' }}
  workflows:
    description: >-
      'true' if '.github/**/*.ya?ml' was modified; otherwise ''
    value: ${{ steps.paths.outputs.workflows == 'true' || '' }}
runs:
  using: composite
  steps:
    - name: Identify modified paths
      id: paths
      uses: dorny/paths-filter@v4
      with:
        ref: ${{ inputs.ref || github.head_ref || github.ref }}
        base: ${{ inputs.base || github.base_ref || '' }}
        filters: |
          compose:
            - compose.yaml
          docker:
            - Dockerfile
            - .dockerignore
          docs:
            - docs/**
            - zensical.toml
          git:
            - .gitattributes
            - .gitignore
          readme:
            - *.md
            - CITATION.cff
            - LICENSE.txt
          setup:
            - pyproject.toml
          src:
            - src/**
          tests:
            - tests/**
          tools:
            - .editorconfig
            - .pre-commit-config.yaml
            - biome.jsonc
            - devcontainer.json
            - justfile
            - bin/
            - scripts/
          workflows:
            - .github/**/*.ya?ml
