# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: publish-mkdocs-to-pages
description: >-
  Builds mkdocs docs and publishes them to GitHub Pages.
  The GitHub context should be a tag but can be a branch.
  Needs permissions: 'contents: write', 'pages: write'.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
    - shell: bash
      run: |
        uv sync --locked --only-group docs
        uv run --no-sync mkdocs build --strict
    # Don't update to v4 until this is fixed:
    # https://github.com/actions/upload-pages-artifact/pull/102
    # https://github.com/actions/upload-pages-artifact/issues/129
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .site
    - uses: actions/deploy-pages@v4
