# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: check-pr-metadata
description: >-
  Verifies the PR title, body, and linked issues.
  Needs PR read permission.
# TODO: This is only a sketch.
inputs:
  pr:
    required: true
    description: The PR number.

outputs:
  type:
    description: The commit type.
    value: ${{ steps.label.outputs.type }}
  scopes:
    description: A comma-separated list of scopes.
    value: ${{ steps.label.outputs.scope }}
  breaking-change:
    description: The 'BREAKING CHANGE' summary, if any.
    value: ${{ steps.label.outputs.breaking }}
  deprecated:
    description: The 'DEPRECATED' summary, if any.
    value: ${{ steps.label.outputs.deprecated }}
  reverts:
    description: The commit sha1 in 'This commit reverts', if any.
    value: ${{ steps.label.outputs.reverts }}
  closes:
    description: The number of the issue in the 'Closes' trailer, if any.
    value: ${{ steps.label.outputs.closes }}
  linked:
    description: A comma-separated list of linked issue and PR numbers.
    value: ${{ steps.label.outputs.linked }}

runs:
  using: composite
  steps:
    - id: label
      # TODO: This Action is inflexible and should be replaced with some regex and the GH CLI.
      uses: amannn/action-semantic-pull-request@v5
      with:
        types: |
          feat
          security
          drop
          depr
          fix
          perf
          build
          docs
          refactor
          test
          ci
          style
          chore
        scopes: |
          dev-infra
          docs-infra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # See: https://github.com/github/docs/issues/21930
