# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "📚 Documentation"
description: "Documentation issue"
labels:
  - "type: docs"

body:
  - type: textarea
    id: description
    attributes:
      label: What documentation needs work?
      placeholder: Describe the documentation issue.
      render: markdown
    validations:
      required: true
