# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "✨ Feature"
description: "Feature request"
labels:
  - "type: feature"

body:
  - type: textarea
    id: description
    attributes:
      label: What is the feature request?
      placeholder: Describe the feature.
      render: markdown
    validations:
      required: true
