# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "⚡️ Performance"
description: "Performance issue"
labels:
  - "type: performance"

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Detail what you tried and how performance was affected.
      render: markdown
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version(s) are affected?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) do you see the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Android
        - iOS
        - other
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) do you see the problem on?
      multiple: true
      options:
        - Chromium (Chrome, Edge, …)
        - Gecko (Firefox)
        - Safari
        - other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
