# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: lint-python
description: >-
  Lints Python source and related files.
  Needs permissions: 'contents: read'.

inputs:
  ref:
    default: ""
    description: A branch or tag ref; defaults to github.head_ref then to github.ref.
  glob:
    default: .
    description: Glob of files to lint. Unrecognized file types are ignored.
  ruff-rules:
    default: ""
    description: Ruff rule specifier passed as 'ruff check --select <rules>'.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref || github.head_ref || github.ref }}
    - uses: astral-sh/setup-uv@v7
    - shell: bash
      run: |
        uv sync --locked --only-group lint
    - name: Check Ruff rules
      env:
        FILES: ${{ inputs.glob || '.' }}
        RULES: ${{ inputs.rules }}
      shell: bash
      run: |
        if [[ -z "$RULES" ]]; then
          uv run --no-sync ruff check --no-fix "$FILES"
        else
          uv run --no-sync ruff check --no-fix --select "$RULES" "$FILES"
        fi
    - name: Check Ruff formatting.
      shell: bash
      env:
        FILES: ${{ inputs.glob || '.' }}
      run: |
        uv run --no-sync ruff format --check "$FILES"
    - name: Check Deal rules (if set up).
      shell: bash
      env:
        FILES: ${{ inputs.glob || '.' }}
      run: |
        if uv run --no-sync python -m deal --help >> /dev/null; then
          uv run --no-sync python -m deal lint "$FILES"
        fi
    - name: Check typing with ty.
      shell: bash
      env:
        FILES: ${{ inputs.glob || '.' }}
      run: |
        uv run --no-sync ty check "$FILES"
