# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# When a commit is pushed to main or releases/**,
# runs tests and either opens an issue or uploads coverage reports.
name: main-test
run-name: Test ${{ github.ref_name }} (${{ github.sha }})

on:
  push:
    paths:
      - pyproject.toml
      - src/**/*.py
      - tests/**/*.py
    branches:
      - main
      - master
      - releases/**

concurrency:
  group: ${{ github.workflow }} / ${{ github.ref }}
  # More restrictive groups defined on jobs.

permissions:
  contents: read

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  #
  test:
    uses: ./.github/workflows/_test-pytest-matrix.yaml
    with:
      retention-days: 1 # Only to upload coverage reports.

  create-issue:
    if: ${{ needs.test.result == 'success' }}
    needs: test
    permissions:
      issues: write
    name: Open a GitHub issue if tests failed
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # See: https://github.com/github/docs/issues/21930
        shell: bash
        run: |
          gh issue create \
            --title "Test failure(s) on $GITHUB_REF_NAME" \
            --body "See: [run #$GITHUB_RUN_ID]($RUN_URL)" \
            --label "type: bug"

  update-codecov:
    if: ${{ env.CODECOV_TOKEN }}
    needs: test
    uses: ./.github/workflows/_update-codecov.yaml
    secrets: inherit

  update-coveralls:
    if: ${{ env.COVERALLS_TOKEN }}
    needs: test
    uses: ./.github/workflows/_update-coveralls.yaml
    secrets: inherit
