# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Responds to `/plz <command>` comments on pull requests.
name: pr-bot
run-name: PR ${{ github.event.pull_request.number }} comment by ${{ github.sender.login }}

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read

env:
  NULLARY_CMD: >-
    ^\/plz ++(?<cmd>[a-z0-9 -]++) *+$
  UNARY_CMD: >-
    ^\/plz ++(?<cmd>(?:(?:[a-z0-9-]++) *)+?)(?: ++(?:in|on)?+ ++(?<ref>head|merge)(?: ref)?+)?+ *+$

jobs:
  # Parse the body and find lines matching `/plz <cmd> [<ref>]`.
  # Individual jobs could check e.g. `contains(github.event.comment.body, '/plz test')`.
  # However, that can't capture command "arguments" (though, currently, we only need `<ref>`).
  # Note that we allow multiple commands per comment.
  # To associate arguments with their respective commands, we need Bash for regex, etc.
  # TODO: We need more robust parsing.
  cmd:
    if: ${{ github.event.issue.pull_request }}
    name: Parse comment cmd
    runs-on: ubuntu-latest
    env:
      TEXT: ${{ github.event.comment.body }}
    outputs:
      nullary: ${{ steps.extract.outputs.nullary }}
      unary: ${{ steps.extract.outputs.unary }}
    steps:
      - name: Extract commands using regex
        id: extract
        shell: bash
        run: |
          nullary=$( \
            grep --only-matching --perl-regexp "$NULLARY_CMD" <<< "$TEXT" \
              | sed -E 's/-/ /g' | sed -E 's/plz ++//g' \
              | sed -E 's/reformat/format/g'
          )
          echo "nullary=$nullary" >> "$GITHUB_OUTPUT"
          unary=$( \
            grep --only-matching --perl-regexp "$UNARY_CMD" <<< "$TEXT" \
            | sed -E 's/-/ /g' | sed -E 's/plz ++//g' | sed -E 's/ ++(in|on) ++/ \//g' \
          )
          echo "unary=$unary" >> "$GITHUB_OUTPUT"

  audit:
    if: ${{ contains(needs.cmd.outputs.unary, 'audit') }}
    needs: cmd
    uses: ./.github/actions/lint-python/action.yaml
    with:
      ruff-rules: S
      # Run on HEAD, unless "on merge" is specifically requested.
      ref: >-
        ${{ contains(needs.cmd.outputs.unary, 'audit /merge') && github.ref || github.head_ref }}

  lint:
    if: ${{ contains(needs.cmd.outputs.unary, 'lint') }}
    needs: cmd
    runs-on: ubuntu-latest
    env:
      # Run on HEAD, unless "on merge" is specifically requested.
      R: ${{ contains(needs.cmd.outputs.unary, 'lint /merge') && github.ref || github.head_ref }}
    steps:
      - uses: ./.github/actions/lint-python/action.yaml
        with:
          ref: ${{ env.R }}
      - uses: ./.github/actions/lint-dockerfile/action.yaml
        with:
          ref: ${{ env.R }}
      - uses: ./.github/actions/lint-data-files/action.yaml
        with:
          ref: ${{ env.R }}
      - uses: ./.github/actions/lint-helm-charts/action.yaml
        with:
          ref: ${{ env.R }}

  check-image:
    if: ${{ contains(needs.cmd.outputs.unary, 'check image') }}
    needs: cmd
    uses: ./.github/workflows/_test-docker.yaml
    with:
      # Run on HEAD, unless "on merge" is specifically requested.
      ref: >-
        ${{ contains(needs.cmd.outputs.unary, 'check image /merge') && github.ref || github.head_ref }}

  check-docs:
    if: ${{ contains(needs.cmd.outputs.unary, 'check docs') }}
    needs: cmd
    uses: ./.github/actions/check-mkdocs/action.yaml
    with:
      # Run on HEAD, unless "on merge" is specifically requested.
      ref: >-
        ${{ contains(needs.cmd.outputs.unary, 'check docs /merge') && github.ref || github.head_ref }}

  test:
    if: ${{ contains(needs.cmd.outputs.unary, 'test') }}
    needs: cmd
    uses: ./.github/workflows/_test-pytest-matrix.yaml
    with:
      # Run on MERGE, unless "on head" is specifically requested.
      ref: >-
        ${{ contains(needs.cmd.outputs.unary, 'test /head') && github.head_ref || github.ref }}

  upgrade:
    if: ${{ contains(needs.cmd.outputs.nullary, 'upgrade') }}
    needs: cmd
    permissions:
      contents: write
    uses: ./.github/actions/do-bump-dependencies/action.yaml
    with:
      # Always run on HEAD (doesn't make sense on merge).
      ref: ${{ github.head_ref }}

  format:
    if: ${{ contains(needs.cmd.outputs.nullary, 'format') }}
    needs: cmd
    permissions:
      contents: write
    uses: ./.github/actions/do-auto-format/action.yaml
    with:
      # Always run on HEAD (doesn't make sense on merge).
      ref: ${{ github.head_ref }}
      compare-to-ref: ${{ github.base_ref }}
      push: true
