# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Syncs metadata and labels on GitHub to `.github/project.yaml`.
name: sync-repo
run-name: Sync repo metadata for ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/project.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    permissions:
      contents: write
      issues: write
    uses: ./.github/actions/sync-repo-info/action.yaml
